英語翻訳ファイルを作成
actlaboratory/LAMP pull request #54
Opened 2020-12-22 15:05 UTC by kitabatake1013

「未翻訳」（fuzzy）としている箇所が幾つかあります。

2020-12-22 15:43 UTC, yncat commented
fuzzyタグが、公式でいうところの

> 翻訳者が後で再検討する必要があるエントリーを覚えておくために、彼女自身の都合でエントリーをfuzzyとすることもあります。

この目的で使われていると想定してレビューします

ref: https://ayatakesi.github.io/gettext/0.18.3/html/Fuzzy-Entries.html

2020-12-23 16:09 UTC, yncat requested changes
コメントしました。
contact the developer系は、後ろに for further assistance とかを付けるとより親切かも。

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "&About Now Playing"
About the file currently playing

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"Save as m3u8 playlist file?"
save as an m3u8

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"Overwrite?"
ちゃんと分にしましょう
Do you wish to overwrite?

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"Save as playlist file?"
ここも文にしましょう

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "早送り(&F)"
fast-forward

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Go &Backward"
rewind

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "グローバルホットキー設定(&G)"
hotkey は繋げて書くのが一般的です

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Check for &Update"
check for updates が一般的です

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"%s is registered in send to.\n"
registered in で "** の中で登録されている」になってしまうので、 %s is already located in sendto かな

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Following will be carried out after all tracks is played.\n"
after all tracks have finished playing

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"Following will be carried out after all items in playback queue are played.\n"
これも have finished playing

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Connection timeout."
timed out

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Request parameter is invalid. Contact to the developer."
please contact the developer
(to はいりません))

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Updater is not registered. Contact to the developer."
please contact the developer

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"File association information has successfully written.\r\n"
has successfully been written

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "File association information was removed."
has been removed

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"Check the preferred items \n"
Check files that you want to register LAMP as default app

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"%(key)s is configured in following items.\n"
文脈的には、 already とかがあるといいのかな

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Parameter count is invalid."
number of parameters is invalid

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "This %s is already registered. Overwrite?"
Do you wish to overwrite?

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "項目名と初期値の指定件数が一致しません。"
fuzzy タグがない未翻訳エントリ

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "%sを空白や半角の=を含む値に設定することはできません。"
fuzzyなし、未翻訳エントリ

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"%(v1)s、%(v2)sなど計%(count)d箇所に同じショートカットキー%(key)sが設定されて"
未翻訳

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Configured shortcut %s cannot be recognized. Contact to developer.\n"
Please contact the developer

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Failed to load following files."
the following files

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "unfound files"
files could not be found

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"hot key is invalid. Please check for conflicting / unusable key combinations "
hotkey と繋げるのが一般的です

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "history(less than 20 items)"
up to 20 items

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "&Operations"
プレイヤーでは control が一般的です

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "open URL"
ここは複数形じゃなくていいんでしょうか。

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Such path does not exist."
The specified path does not exist.

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "auto selection"
読み上げ方法の設定だったら、 auto detect が多く使われてますかね

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "新たなファイルにより開かれたとき(&F)"
未翻訳。日本語が分かりにくい。

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgid "新たなプレイリストにより開かれたとき(&P)"
未翻訳。日本語が分かりにくい。

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Automatically Check for &Update"
check for updates

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "after specific time"
specified time has elapsed

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "after playing specific amount of tracks"
playing specified number of tracks

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "&Sleep Requirements"
requirements は、要件。条件は、conditions。

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "set amount of tracks"
number of tracks

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "playback tracks is not found."
There are no tracks to play.

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "Updater.exe is not found."
could not be found.

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +msgstr "developer"
developers

2020-12-23 16:09 UTC, yncat commented on locale/en-us/LC_MESSAGES/messages.po
> +"本ソフトウェアには、他の団体または個人の成果物が含まれている場合があります。"
未翻訳

2020-12-27 09:40 UTC, kitabatake1013 commented
修正しました。
最終チェックをお願いします。

2020-12-27 11:13 UTC, yncat approved these changes
LGTM!!!!!!

2020-12-27 11:54 UTC, merged